### ISSUE TITLE
Value to long for type character varying(1024)

### ISSUE THREAD

**Issue by rrauenza** [leandrosouza/django-simple-audit#22]
I think the audited data is just too long for the column -- but which column?  Is it description in simple_audit?

```
ERROR:simple_audit.signal:Error registering auditing to <Maintenance: Maintenance object>: (<class 'app.submodels.common.Maintenance'>) {'comment': u'A VERY LONG STRING', user_id': 14, '_user_cach
e': <User: somebody>, '_state': <django.db.models.base.ModelState object at 0x7f2e98791f10>, 'name_id': 20, 'expire': None, 'time': datetime.datetime(2015, 2, 7, 21, 32, 14, 749289), 'id': 
704}
Traceback (most recent call last):
  File "..../virtualenv/lib/python2.7/site-packages/simple_audit/signal.py", line 255, in save_audit
    change.save()
  File "..../virtualenv/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "..../virtualenv/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "..../virtualenv/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "..../virtualenv/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "..../virtualenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)
  File "..../virtualenv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 58, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "..../virtualenv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)
DatabaseError: value too long for type character varying(1024)
```

**Comment by rrauenza** [comment]
Ah, no, it's AuditChange, old_value/new_value.

**Comment by rrauenza** [comment]
I see the type got changed to textfield -- will try upgrading:

```
class AuditChange(models.Model):
    audit = models.ForeignKey(Audit, related_name='field_changes')
    field = models.CharField(max_length=255)
    old_value = models.TextField(null=True, blank=True)
    new_value = models.TextField(null=True, blank=True)
```

**Comment by rrauenza** [comment]
Upgrade to 1.19 fixed it
