### ISSUE TITLE
Django 1.9 support?

### ISSUE THREAD

**Issue by rrauenza** [leandrosouza/django-simple-audit#23]
When incorporating this into a Django 1.9 project, I get the following error:

django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

```
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/simple_audit/__init__.py", line 1, in <module>
    from .signal import register
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/simple_audit/signal.py", line 9, in <module>
    from .models import Audit, AuditChange
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/simple_audit/models.py", line 9, in <module>
    from .managers import AuditManager
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/simple_audit/managers.py", line 3, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 161, in <module>
    class ContentType(models.Model):
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/proj/virtualenv-2.7.5/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by kobymeir** [comment]
This project currently doesn't support Django 1.9
Please have a look at this fork:
https://github.com/stratasan/django-simple-audit/commits/master

And this is the specific commit (https://github.com/stratasan/django-simple-audit/commit/4266d2d43db76f38ab0cdcdf67c99988e06ea2dc) that adds support to Django 1.9, Have a look specifically at this file for usage example `testproject/simple_app/apps.py`
